### ISSUE TITLE
Wrong margin-top unit

### ISSUE THREAD

**Issue by johnnygerard** [Cool-Runningz/range-input.css#2]
The `margin-top` property should not use `px` units.

When visiting your CSS generator at https://range-input-css.netlify.app/, we see this CSS declaration:

```css
  margin-top: -4px; /* Centers thumb on the track */
```

When using `rem` units for the track or thumb heights, this margin will remain the same when a user selects a non-default font-size. The thumb won't be vertically centered.

So it seems that `calc` should be used for `margin-top`:

```css
  margin-top: calc((var(--track-height) - var(--thumb-height)) / 2); /* Centers thumb on the track */
```

**Comment by johnnygerard** [comment]
I created a Sass mixin that replicates the functionality of your CSS generator while providing a fix for the `margin-top` unit.  
The CSS output can be inspected at [this Sass playground URL](https://sass-lang.com/playground/#eJzNVW1r2zAQ/p5fcbRjJCNqko6NojAoK8vXwvax7INsnxNRWzJ6adON/ffpxY6tJN4YjDEbg3R3Oj/33HP2anVb8z0XoJjYIuGisWY6AXhlFMsfSS4rqeb9/pkXZjfY75Bvd2ZgyKQqUBHFCm51tO9snQ0Thf0gUdgPEwVDkmgyg+/OFdA9mJcGP1wEvBdfgx1g8aa/4CPTWHGBc1Co0YA2LxVqGIQswiHyjNkjN4Q1DTKXL0cKQgpcB+95a+aK3CppRUHBVSx0wxQKE525VVoqCo3kwqCKxlApTQhcT1rQ8Blr+eSwFVgyWxkoZW4d0ojvNY3bWCKAtMaXNYTzY5KWD3c7JWtX+RdWMsXncN+gYsBEAZ+KLUY3t/UxJ4sOkK64ox0C2B4H7aiKbqKsECyrkMS4DmBPTuw3TWS07qKGnaVnhdOFRlXQVG1HlR8ge9mMQ47uDulo633C+ydUyh06dKWS8kDGmDAAaqa2XBAjGwo5q/JpaweYJviBpKKfwQKu29hZAHCHXj66LUkKt8C0Jee57idtlOvT2TrleoCtcx5E3A9v0oZWqr9h/SDgt80etHQhZ0G3YUSWpRtfCsur1fU7hfV5yXvVb7jCUu5HJ/0Xwq7lNxK/ff+zlgcoE0b/RAW9wruvDu4dltbr3skMbDZe3hVH3Qvtn0torNi/JB//uHfecpFX1k350Z/vkhXFDb73v6JwzC+WV6ery5ulv/1y1ZpWSdBktv4J3AkzkQ==).

```scss
@mixin range-input(
  $track-color,
  $track-width,
  $track-height,
  $track-border-radius,
  $thumb-color,
  $thumb-width,
  $thumb-height,
  $thumb-border-radius
) {
  input[type="range"] {
    /*********** Baseline, reset styles ***********/
    -webkit-appearance: none;
    appearance: none;
    background: transparent;
    cursor: pointer;
    width: $track-width;

    /* Removes default focus */
    &:focus {
      outline: none;
    }

    /******** Chrome, Safari, Opera and Edge Chromium styles ********/
    /* slider track */
    &::-webkit-slider-runnable-track {
      background-color: $track-color;
      border-radius: $track-border-radius;
      height: $track-height;
    }

    /* slider thumb */
    &::-webkit-slider-thumb {
      -webkit-appearance: none; /* Override default look */
      appearance: none;
      margin-top: calc(
        ($track-height - $thumb-height) / 2
      ); /* Centers thumb on the track */
      background-color: $thumb-color;
      border-radius: $thumb-border-radius;
      height: $thumb-height;
      width: $thumb-width;
    }

    &:focus::-webkit-slider-thumb {
      outline: 3px solid $thumb-color;
      outline-offset: 0.125rem;
    }

    /*********** Firefox styles ***********/
    /* slider track */
    &::-moz-range-track {
      background-color: $track-color;
      border-radius: $track-border-radius;
      height: $track-height;
    }

    /* slider thumb */
    &::-moz-range-thumb {
      background-color: $thumb-color;
      border: none; /*Removes extra border that FF applies*/
      border-radius: $thumb-border-radius;
      height: $thumb-height;
      width: $thumb-width;
    }

    &:focus::-moz-range-thumb {
      outline: 3px solid $thumb-color;
      outline-offset: 0.125rem;
    }
  }
}
```
